repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3

  # TODO: Re-enable tests after fixing API compatibility issues
  # Tests are temporarily disabled due to federation API changes
  # - repo: local
  #   hooks:
  #     - id: pytest-local
  #       name: Run tests
  #       entry: bash -c 'cd /Users/kreme003/Workspace/git/edugain-qual-improv && source .venv/bin/activate && python -m pytest tests/ -v'
  #       language: system
  #       pass_filenames: false
  #       always_run: true
