"""Configuration modules."""

from .settings import (
    EDUGAIN_FEDERATIONS_API,
    EDUGAIN_METADATA_URL,
    FEDERATION_CACHE_DAYS,
    FEDERATION_CACHE_FILE,
    MAX_CONTENT_SIZE,
    METADATA_CACHE_FILE,
    METADATA_CACHE_HOURS,
    NAMESPACES,
    REQUEST_TIMEOUT,
    URL_VALIDATION_CACHE_DAYS,
    URL_VALIDATION_CACHE_FILE,
    URL_VALIDATION_DELAY,
    URL_VALIDATION_THREADS,
    URL_VALIDATION_TIMEOUT,
)

__all__ = [
    "EDUGAIN_METADATA_URL",
    "EDUGAIN_FEDERATIONS_API",
    "METADATA_CACHE_FILE",
    "METADATA_CACHE_HOURS",
    "FEDERATION_CACHE_FILE",
    "FEDERATION_CACHE_DAYS",
    "URL_VALIDATION_CACHE_FILE",
    "URL_VALIDATION_CACHE_DAYS",
    "REQUEST_TIMEOUT",
    "URL_VALIDATION_TIMEOUT",
    "URL_VALIDATION_DELAY",
    "URL_VALIDATION_THREADS",
    "MAX_CONTENT_SIZE",
    "NAMESPACES",
]
